CREATE DATABASE IF NOT EXISTS $AUTH_DB ;
CREATE DATABASE IF NOT EXISTS $CERT_DB;
CREATE DATABASE IF NOT EXISTS $ANSPAR_DB;


CREATE USER IF NOT EXISTS '$AUTH_USER' IDENTIFIED BY '$AUTH_PASS';
CREATE USER IF NOT EXISTS '$CERT_USER' IDENTIFIED BY '$CERT_PASS';
CREATE USER IF NOT EXISTS '$ANSPAR_USER' IDENTIFIED BY '$ANSPAR_PASS';


GRANT ALL PRIVILEGES ON $AUTH_DB.*  TO '$AUTH_USER'@'%';
GRANT ALL PRIVILEGES ON $CERT_DB.*  TO '$CERT_USER'@'%';
GRANT ALL PRIVILEGES ON $ANSPAR_DB.*  TO '$ANSPAR_USER'@'%';

